global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'flask_app'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['host.docker.internal:5000']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
