# Generated by Django 5.0.1 on 2026-01-20 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentTelemetryEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ts_unix", models.FloatField(db_index=True)),
                ("trace_id", models.CharField(db_index=True, max_length=64)),
                ("agent_name", models.CharField(db_index=True, max_length=64)),
                ("agent_version", models.CharField(max_length=32)),
                ("model_name", models.CharField(db_index=True, max_length=128)),
                ("latency_ms", models.IntegerField()),
                ("outcome", models.CharField(db_index=True, max_length=32)),
                ("reason_code", models.CharField(db_index=True, max_length=64)),
                ("prompt_tokens", models.IntegerField(blank=True, null=True)),
                ("completion_tokens", models.IntegerField(blank=True, null=True)),
                ("total_tokens", models.IntegerField(blank=True, null=True)),
                ("estimated_cost_usd", models.FloatField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-ts_unix"],
                "indexes": [
                    models.Index(
                        fields=["agent_name", "ts_unix"], name="fitmaster_a_agent_n_940caf_idx"
                    ),
                    models.Index(
                        fields=["outcome", "ts_unix"], name="fitmaster_a_outcome_57e7d0_idx"
                    ),
                ],
            },
        ),
    ]
