# Generated by Django 5.0.1 on 2026-01-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bioanalyze", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NutritionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("daily_calories", models.FloatField(verbose_name="Daily Calories")),
                ("protein_grams", models.FloatField(verbose_name="Protein (g)")),
                ("carbs_grams", models.FloatField(verbose_name="Carbs (g)")),
                ("fats_grams", models.FloatField(verbose_name="Fats (g)")),
                (
                    "plan_data",
                    models.JSONField(
                        blank=True,
                        help_text="Detailed meal plan, recipes, and recommendations",
                        null=True,
                        verbose_name="Plan Data",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "biometric_analysis",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="nutrition_plans",
                        to="bioanalyze.biometricanalysis",
                        verbose_name="Biometric Analysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nutrition Plan",
                "verbose_name_plural": "Nutrition Plans",
                "db_table": "nutrition_plans",
                "ordering": ["-created_at"],
            },
        ),
    ]
