# Generated by Django 5.0.1 on 2026-01-12 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("nutrition", "0001_initial"),
        ("organizations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="nutritionplan",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nutrition_plans",
                to="organizations.organization",
                verbose_name="Organization",
            ),
        ),
    ]
