# Generated by Django 5.0.1 on 2026-01-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Membership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("invited_at", models.DateTimeField(auto_now_add=True, verbose_name="Invited At")),
                (
                    "accepted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Accepted At"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Membership",
                "verbose_name_plural": "Memberships",
                "db_table": "memberships",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Organization Name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="Slug")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("gym", "Gym/Fitness Center"),
                            ("nutritionist", "Nutritionist Practice"),
                            ("trainer", "Personal Trainer"),
                            ("corporate", "Corporate"),
                        ],
                        default="individual",
                        max_length=50,
                        verbose_name="Organization Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="organizations/logos/", verbose_name="Logo"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Contact Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Contact Phone"
                    ),
                ),
                ("website", models.URLField(blank=True, null=True, verbose_name="Website")),
                ("address", models.TextField(blank=True, null=True, verbose_name="Address")),
                (
                    "city",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="City"),
                ),
                (
                    "country",
                    models.CharField(blank=True, max_length=100, null=True, verbose_name="Country"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium", "Premium"),
                            ("pro", "Pro"),
                            ("business", "Business"),
                        ],
                        default="free",
                        max_length=50,
                        verbose_name="Subscription Plan",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Organization",
                "verbose_name_plural": "Organizations",
                "db_table": "organizations",
                "ordering": ["-created_at"],
            },
        ),
    ]
