# Generated by Django 5.0.1 on 2026-01-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BiometricAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("weight", models.FloatField(verbose_name="Weight (kg)")),
                ("height", models.FloatField(verbose_name="Height (cm)")),
                ("age", models.IntegerField(verbose_name="Age")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "Male"), ("female", "Female"), ("other", "Other")],
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                ("neck", models.FloatField(verbose_name="Neck (cm)")),
                ("waist", models.FloatField(verbose_name="Waist (cm)")),
                ("hip", models.FloatField(blank=True, null=True, verbose_name="Hip (cm)")),
                (
                    "biceps_left",
                    models.FloatField(blank=True, null=True, verbose_name="Left Biceps (cm)"),
                ),
                (
                    "biceps_right",
                    models.FloatField(blank=True, null=True, verbose_name="Right Biceps (cm)"),
                ),
                (
                    "thigh_left",
                    models.FloatField(blank=True, null=True, verbose_name="Left Thigh (cm)"),
                ),
                (
                    "thigh_right",
                    models.FloatField(blank=True, null=True, verbose_name="Right Thigh (cm)"),
                ),
                (
                    "calf_left",
                    models.FloatField(blank=True, null=True, verbose_name="Left Calf (cm)"),
                ),
                (
                    "calf_right",
                    models.FloatField(blank=True, null=True, verbose_name="Right Calf (cm)"),
                ),
                (
                    "activity_factor",
                    models.FloatField(blank=True, null=True, verbose_name="Activity Factor"),
                ),
                (
                    "activity_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("sedentary", "Sedentary"),
                            ("light", "Light"),
                            ("moderate", "Moderate"),
                            ("active", "Active"),
                            ("very_active", "Very Active"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Activity Level",
                    ),
                ),
                (
                    "goal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("lose_weight", "Lose Weight"),
                            ("maintain", "Maintain"),
                            ("gain_muscle", "Gain Muscle"),
                        ],
                        max_length=32,
                        null=True,
                        verbose_name="Goal",
                    ),
                ),
                ("bmi", models.FloatField(blank=True, null=True, verbose_name="BMI")),
                ("bmr", models.FloatField(blank=True, null=True, verbose_name="BMR")),
                ("tdee", models.FloatField(blank=True, null=True, verbose_name="TDEE")),
                (
                    "body_fat_percentage",
                    models.FloatField(blank=True, null=True, verbose_name="Body Fat %"),
                ),
                (
                    "lean_mass",
                    models.FloatField(blank=True, null=True, verbose_name="Lean Mass (kg)"),
                ),
                (
                    "fat_mass",
                    models.FloatField(blank=True, null=True, verbose_name="Fat Mass (kg)"),
                ),
                ("ffmi", models.FloatField(blank=True, null=True, verbose_name="FFMI")),
                (
                    "body_water",
                    models.FloatField(blank=True, null=True, verbose_name="Body Water %"),
                ),
                ("waist_hip_ratio", models.FloatField(blank=True, null=True, verbose_name="WHR")),
                (
                    "waist_height_ratio",
                    models.FloatField(blank=True, null=True, verbose_name="WHtR"),
                ),
                (
                    "metabolic_age",
                    models.FloatField(blank=True, null=True, verbose_name="Metabolic Age"),
                ),
                (
                    "maintenance_calories",
                    models.FloatField(blank=True, null=True, verbose_name="Maintenance Calories"),
                ),
                (
                    "protein_grams",
                    models.FloatField(blank=True, null=True, verbose_name="Protein (g)"),
                ),
                ("carbs_grams", models.FloatField(blank=True, null=True, verbose_name="Carbs (g)")),
                ("fats_grams", models.FloatField(blank=True, null=True, verbose_name="Fats (g)")),
                (
                    "fitmaster_data",
                    models.JSONField(
                        blank=True,
                        help_text="Complete AI interpretation, nutrition plan, and training plan",
                        null=True,
                        verbose_name="FitMaster AI Data",
                    ),
                ),
                (
                    "front_photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Front Photo"),
                ),
                (
                    "back_photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Back Photo"),
                ),
                (
                    "side_photo_url",
                    models.URLField(blank=True, null=True, verbose_name="Side Photo"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
            ],
            options={
                "verbose_name": "Biometric Analysis",
                "verbose_name_plural": "Biometric Analyses",
                "db_table": "biometric_analyses",
                "ordering": ["-created_at"],
            },
        ),
    ]
