# Generated by Django 5.0.1 on 2026-01-12 00:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bioanalyze", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="biometricanalysis",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="biometric_analyses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AddIndex(
            model_name="biometricanalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="biometric_a_user_id_13b890_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricanalysis",
            index=models.Index(
                fields=["organization", "-created_at"], name="biometric_a_organiz_4d821b_idx"
            ),
        ),
    ]
