"""create biometric_analyses table

Revision ID: 05b1de3e5742
Revises: 9d1d7e9cac33
Create Date: 2025-10-04 17:07:00.786241

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05b1de3e5742'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('biometric_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('neck', sa.Float(), nullable=False),
    sa.Column('waist', sa.Float(), nullable=False),
    sa.Column('hip', sa.Float(), nullable=True),
    sa.Column('activity_factor', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.String(length=32), nullable=True),
    sa.Column('goal', sa.String(length=32), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Float(), nullable=True),
    sa.Column('tdee', sa.Float(), nullable=True),
    sa.Column('body_fat_percentage', sa.Float(), nullable=True),
    sa.Column('lean_mass', sa.Float(), nullable=True),
    sa.Column('fat_mass', sa.Float(), nullable=True),
    sa.Column('ffmi', sa.Float(), nullable=True),
    sa.Column('body_water', sa.Float(), nullable=True),
    sa.Column('waist_hip_ratio', sa.Float(), nullable=True),
    sa.Column('waist_height_ratio', sa.Float(), nullable=True),
    sa.Column('metabolic_age', sa.Float(), nullable=True),
    sa.Column('maintenance_calories', sa.Float(), nullable=True),
    sa.Column('protein_grams', sa.Float(), nullable=True),
    sa.Column('carbs_grams', sa.Float(), nullable=True),
    sa.Column('fats_grams', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_biometric_analyses_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_biometric_analyses_user_id'))

    op.drop_table('biometric_analyses')
    # ### end Alembic commands ###
