"""real_telegram_and_usage_tables

Revision ID: 0aafee66b26c
Revises: create_notifications
Create Date: 2026-02-20 21:06:59.208943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aafee66b26c'
down_revision = 'create_notifications'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_usage_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('llm_usage_ledger', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_llm_usage_ledger_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_conversation_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'system', name='message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_conversation_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_conversation_messages_user_id'), ['user_id'], unique=False)

    op.create_table('telegram_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('telegram_link_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_telegram_link_tokens_token'), ['token'], unique=True)

    op.create_table('user_telegram_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.String(length=50), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('pending', 'verified', 'revoked', name='telegram_link_status'), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('user_telegram_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_telegram_links_telegram_user_id'), ['telegram_user_id'], unique=True)

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)

    with op.batch_alter_table('user_telegram_links', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_telegram_links_telegram_user_id'))

    op.drop_table('user_telegram_links')
    with op.batch_alter_table('telegram_link_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_link_tokens_token'))

    op.drop_table('telegram_link_tokens')
    with op.batch_alter_table('telegram_conversation_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telegram_conversation_messages_user_id'))

    op.drop_table('telegram_conversation_messages')
    with op.batch_alter_table('llm_usage_ledger', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_llm_usage_ledger_user_id'))

    op.drop_table('llm_usage_ledger')
    # ### end Alembic commands ###
