"""add_photo_fields_to_biometric_analysis

Revision ID: 8d34854ebd24
Revises: fa12d24e9741
Create Date: 2025-10-28 11:15:01.094534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d34854ebd24'
down_revision = 'fa12d24e9741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_contact_messages_is_read'))
        batch_op.drop_index(batch_op.f('idx_contact_messages_user_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contact_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_contact_messages_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_contact_messages_is_read'), ['is_read'], unique=False)

    # ### end Alembic commands ###
