"""add ai fields to biometric_analyses

Revision ID: b782377526f4
Revises: 05b1de3e5742
Create Date: 2025-10-05 22:58:16.043801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b782377526f4'
down_revision = '05b1de3e5742'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_interpretation', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('nutrition_plan', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('training_plan', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.drop_column('training_plan')
        batch_op.drop_column('nutrition_plan')
        batch_op.drop_column('ai_interpretation')

    # ### end Alembic commands ###
