"""add_photo_url_fields_to_biometric_analysis

Revision ID: c18eb18a660c
Revises: 8d34854ebd24
Create Date: 2025-10-29 10:41:54.012678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c18eb18a660c'
down_revision = '8d34854ebd24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('front_photo_url', sa.String(length=255), nullable=True, comment='URL of front body photo stored in S3'))
        batch_op.add_column(sa.Column('back_photo_url', sa.String(length=255), nullable=True, comment='URL of back body photo stored in S3'))
        batch_op.add_column(sa.Column('side_photo_url', sa.String(length=255), nullable=True, comment='URL of side body photo stored in S3'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('biometric_analyses', schema=None) as batch_op:
        batch_op.drop_column('side_photo_url')
        batch_op.drop_column('back_photo_url')
        batch_op.drop_column('front_photo_url')

    # ### end Alembic commands ###
