# Generated by Django 5.0.1 on 2026-01-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Format: module.action (e.g., bioanalyze.view_own)",
                        max_length=100,
                        unique=True,
                        verbose_name="Permission Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "module",
                    models.CharField(
                        help_text="Module this permission belongs to (e.g., bioanalyze, nutrition)",
                        max_length=50,
                        verbose_name="Module",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Action allowed (e.g., view_own, create, delete)",
                        max_length=50,
                        verbose_name="Action",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["module", "action"],
                "indexes": [
                    models.Index(fields=["module", "action"], name="permissions_module_8c66f0_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True, verbose_name="Role Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "is_system_role",
                    models.BooleanField(
                        default=False,
                        help_text="System roles cannot be deleted",
                        verbose_name="System Role",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created At")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "permissions",
                    models.ManyToManyField(
                        blank=True,
                        related_name="roles",
                        to="permissions.permission",
                        verbose_name="Permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["name"],
            },
        ),
    ]
